# Generated by Django 4.0.2 on 2022-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile',
            field=models.CharField(default='user_profile', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
