# Generated by Django 4.0.2 on 2022-04-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_id_profile_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, default='seal', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
