# Generated by Django 4.0.2 on 2022-03-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
