# Generated by Django 4.0.2 on 2022-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_closing_date_project_issue_project_science_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
