# Generated by Django 4.0.2 on 2022-04-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_categories_alter_project_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
    ]
